language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

before_script:
  - [ "$TRAVIS_PHP_VERSION" = "5.3.3" ] && composer config disable-tls true
  - [ "$TRAVIS_PHP_VERSION" = "5.3.3" ] && composer config secure-http false
  - [ "$TRAVIS_PHP_VERSION" != "5.3.3" ] && travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script: composer test

after_script:
  - [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && wget https://scrutinizer-ci.com/ocular.phar
  - [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && php ocular.phar code-coverage:upload --format=php-clover reports/coverage.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
